### ISSUE TITLE
If using plymouth, need to use encrypt hook

### ISSUE THREAD

**Issue by Barbarossa93** [kishorv06/arch-mkinitcpio-clevis-hook#1]
Hey there,

Thanks for this hook! This should probably be mentioned on the [wiki page](https://wiki.archlinux.org/index.php/Trusted_Platform_Module). I did want to point out one thing in case others use this with plymouth. On the Arch [wiki page](https://wiki.archlinux.org/index.php/plymouth) regarding plymouth, it says to use the `plymouth-encrypt` instead of `encrypt`. With this `clevis` hook, disregard that. so your hooks should look something like this if using `clevis` and `plymouth`:
```
HOOKS=(base udev plymouth autodetect modconf block clevis encrypt filesystems resume keyboard fsck shutdown)
```
Feel free to close this whenever you see this.

**Comment by kishorv06** [comment]
I am not sure if we should replace `plymouth-encrypt` with `encrypt`. As far as I know, hooks are executed in the same order as they are defined. So if `clevis` was able to unlock your disk both the `encrypt` and `plymouth-encrypt` hooks won't do anything. Otherwise `encrypt` would present you with a terminal input for password where as `plymouth-encrypt` would show one with GUI. So it would be always a good idea to use `plymouth-encrypt` if you are using plymouth. Otherwise you will have to switch using 'Esc' to see the password prompt.

Please correct me if I am wrong.

**Comment by Barbarossa93** [comment]
When I ran with `... clevis plymouth-encrypt...` what happened was that the password prompt would come up even if the tpm unlock was successful. I would have to put in the password 5 times before it continues boot. In the terminal, each attempt failed because the device is already unlocked, booting was only continuing because the unlocking mechanism just "gives up" after 5 tries. When I run with `...clevis encrypt...` after the successful unlock with the tpm, boot continues normally. Technically, yeah, you probably wouldn't want either encrypt hook if clevis is already doing the work, but in the event that it fails, you definitely want at least one of those hooks. Ideally it would be `plymouth-encrypt` when using plymouth, but as I already described, it doesn't work properly. I think what would be ideal then is to fix `plymouth-encrypt` to allow the boot process to continue when the device is already unlocked. The `plymouth-encrypt` hook is a homemade hook that is part of the plymouth AUR package, so you could try reaching out to the [maintainer](https://aur.archlinux.org/packages/plymouth-git/) if they'd be willing to patch their hook

**Comment by kishorv06** [comment]
Ok. In that case your suggestion makes sense. The `plymouth-encrypt` hook might not be expecting the device to be already unlocked. I would include your suggestion in the readme so that it would help others.
